name: Python package

on: [push]

jobs:
  build:

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint --exit-zero py3gpp/*.py | tee pylint.txt
          score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
          echo "Pylint score was $score"
          mkdir badge
          anybadge --value=$score --file=badge/pylint.svg pylint
      - name: upload pylint badge    
        uses: actions/configure-pages@v1
        uses: actions/upload-pages-artifact@v1
          with:
          path: 'badge/pylint.svg'
      - name: Test with pytest
        run: |
          pytest py3gpp/*
